global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'hpe_oneview'
    static_configs:
      - targets: ['hpe-oneview-exporter:8080']

