{
 "title": "HPE OneView",
 "description": "HPE OneView dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of Servers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(oneview_count{resourceType=\"server-hardware\"})"
    }
   ]
  },
  {
   "title": "Servers: OK",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"server-hardware\",status=\"'status'='OK'\"}"
    }
   ]
  },
  {
   "title": "Servers: Warning",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"server-hardware\",status=\"'status'='Warning'\"}"
    }
   ]
  },
  {
   "title": "Servers: Critical",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"server-hardware\",status=\"'status'='Critical'\"}"
    }
   ]
  },
  {
   "title": "Servers: Disabled",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"server-hardware\",status=\"'status'='Disabled'\"}"
    }
   ]
  },
  {
   "title": "Servers: Unknown",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"server-hardware\",status=\"'status'='Unknown'\"}"
    }
   ]
  },
  {
   "title": "No. of Interconnects",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_count{resourceType=\"interconnects\"}"
    }
   ]
  },
  {
   "title": "Number of Enclosures",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_count{resourceType=\"enclosures\"}"
    }
   ]
  },
  {
   "title": "Enclosures: OK",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"enclosures\",status=\"'status'='OK'\"}"
    }
   ]
  },
  {
   "title": "Enclosures: Warning",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"enclosures\",status=\"'status'='Warning'\"}"
    }
   ]
  },
  {
   "title": "Enclosures: Critical",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"enclosures\",status=\"'status'='Critical'\"}"
    }
   ]
  },
  {
   "title": "Enclosures: Disabled",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"enclosures\",status=\"'status'='Disabled'\"}"
    }
   ]
  },
  {
   "title": "Enclosures: Unknown",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"enclosures\",status=\"'status'='Unknown'\"}"
    }
   ]
  },
  {
   "title": "No. of SAS nterconnects",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_count{resourceType=\"sas-interconnects\"}"
    }
   ]
  },
  {
   "title": "SAS Interconnect: OK",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"sas-interconnects\",status=\"'status'='OK'\"}"
    }
   ]
  },
  {
   "title": "SAS Interconnect: Warning",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"sas-interconnects\",status=\"'status'='Warning'\"}"
    }
   ]
  },
  {
   "title": "SAS Interconnect: Critical",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"sas-interconnects\",status=\"'status'='Critical'\"}"
    }
   ]
  },
  {
   "title": "SAS Interconnect: Disabled",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"sas-interconnects\",status=\"'status'='Disabled'\"}"
    }
   ]
  },
  {
   "title": "SAS Interconnect: Unknown",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "oneview_status{resourceType=\"sas-interconnects\",status=\"'status'='Unknown'\"}"
    }
   ]
  },
  {
   "title": "Current Total Average Power Draw",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(oneview_averagePower_watts)\n"
    }
   ]
  },
  {
   "title": "Current Average Enclosures Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(oneview_averagePower_watts{category=\"enclosures\"})\n"
    }
   ]
  },
  {
   "title": "Current Average Servers Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum(oneview_averagePower_watts{category=\"server-hardware\"})\n"
    }
   ]
  },
  {
   "title": "Total  Power Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(oneview_averagePower_watts)",
     "legendFormat": "Average"
    },
    { "expr": "sum(oneview_peakPower_watts)", "legendFormat": "Peak" }
   ]
  },
  {
   "title": "Enclosures  only Power Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(oneview_averagePower_watts{category=\"enclosures\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "sum(oneview_peakPower_watts{category=\"enclosures\"})",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "All Servers Power Consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(oneview_averagePower_watts{category=\"server-hardware\"})",
     "legendFormat": "Average"
    },
    {
     "expr": "sum(oneview_peakPower_watts{category=\"server-hardware\"})",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Enclosures Ambient Temparature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "oneview_ambientTemperature_celcius{category=\"enclosures\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Servers Ambient Temparature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "oneview_ambientTemperature_celcius{category=\"server-hardware\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}